### ISSUE TITLE
Add Custom Header for Logos

### ISSUE THREAD

**Issue by bgardner** [copyblogger/genesis-sample#23]
As discussed.

**Comment by laurenmancke** [comment]
7b5feb4adad15c9ddfffc1aaac08a5dc159760b9

**Comment by dreamwhisper** [comment]
@laurenmancke the header image is not contained within the logo area 
![jennifer s site tagline 2016-05-04 06-04-06](https://cloud.githubusercontent.com/assets/1271053/15011127/19ebaf98-11be-11e6-91ae-d5f44255bcef.png)
doesn't center on mobile.

**Comment by dreamwhisper** [comment]
If you take advantage of the flexible height, then the logo doesn't center on mobile.

```css
.header-image .site-title > a {
	background-position: center !important; /* added */
	background-size: contain !important;
	float: left;
	min-height: 80px;
	width: 100%;
}
```
